networks: 
  backend:
#     type: vxlan
#     vni: 100
#     mtu: 1450

services: 
  app: 
    build:
      context: .
      dockerfile: Dockerfile
      target: fast_api
    ports:
      - "80:80"
    networks:
      - backend
    restart: always
    volumes:
      - ./data/app:/app
    depends_on:
      - db
    container_name: l8-api

  # Mysql Database 
  db: 
    # image: mysql
    build: 
      context: .
      dockerfile: Dockerfile
      target: mysql_db
    # platform: linux/x86_64
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/myData:/myData
    networks:
      - backend
    restart: always
    container_name: l8-db
    expose:
      - "3306"

  # Nice Looking webserver uses fastAPI to get the data. 
  nginx:
    # image: nginx
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx_alpine
    ports:
      - "8080:80"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    restart: "always"
    container_name: l8-nginx
    depends_on:
      - db
  #PHP-MYADMIN:
  adminer:
    image: adminer
    restart: always
    networks: 
      - backend
    ports:
      - 8081:8080
    depends_on:
      - db
      
    
      # GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'; FLUSH PRIVILEGES;