# Code generated by:
# python -m pwiz -e mysql -u root -H db -i -o -P db1
# Date: November 14, 2021 09:11PM
# Database: db1
# Peewee version: 3.14.8

from peewee import *

database = MySQLDatabase('db1', **{'charset': 'utf8', 'sql_mode': 'PIPES_AS_CONCAT', 'use_unicode': True, 'host': 'db', 'user': 'root', 'password': 'example'})

class UnknownField(object):
    def __init__(self, *_, **__): pass

class BaseModel(Model):
    class Meta:
        database = database

class Playlists(BaseModel):
    pl_name = CharField()
    pl_followers = IntegerField(constraints=[SQL("DEFAULT 0")])
    pl_duration = IntegerField(constraints=[SQL("DEFAULT 0")])
    pl_num_tracks = IntegerField(constraints=[SQL("DEFAULT 0")])
    pl_modified = DateTimeField(constraints=[SQL("DEFAULT CURRENT_TIMESTAMP")])
    pl_num_artists = IntegerField(constraints=[SQL("DEFAULT 0")], null=True)
    pl_num_albums = IntegerField(constraints=[SQL("DEFAULT 0")], null=True)
    pl_edits = IntegerField(constraints=[SQL("DEFAULT 0")], null=True)
    pl_id = CharField(null=True)
    pl_description = CharField(null=True)
    pl_owner = CharField(null=True)
    pl_owner_url = CharField(null=True)

    class Meta:
        table_name = 'playlists'
        primary_key = False

class Tracks(BaseModel):
    t_artists = CharField()
    t_uri = CharField(primary_key=True)
    t_artist_uri = CharField()
    t_name = CharField()
    t_album_uri = CharField()
    t_duration = IntegerField()
    t_album = CharField()

    class Meta:
        table_name = 'tracks'

