# Code generated by:
# python -m pwiz -e mysql -u root -H db -i -o -P db1
# Date: November 19, 2021 11:53PM
# Database: db1
# Peewee version: 3.14.8

from peewee import *

database = MySQLDatabase('db1', **{'charset': 'utf8', 'sql_mode': 'PIPES_AS_CONCAT', 'use_unicode': True, 'host': 'db', 'user': 'root', 'password': 'example'})

class UnknownField(object):
    def __init__(self, *_, **__): pass

class BaseModel(Model):
    class Meta:
        database = database

class PlaylistContents(BaseModel):
    playlist_id = IntegerField()
    track_uri = CharField()

    class Meta:
        table_name = 'playlist_Contents'
        indexes = (
            (('playlist_id', 'track_uri'), True),
        )
        primary_key = CompositeKey('playlist_id', 'track_uri')

class Playlists(BaseModel):
    pl_description = CharField(null=True)
    pl_duration = IntegerField(constraints=[SQL("DEFAULT 0")])
    pl_edits = IntegerField(constraints=[SQL("DEFAULT 0")])
    pl_followers = IntegerField(constraints=[SQL("DEFAULT 0")])
    pl_id = AutoField()
    pl_modified = DateTimeField(constraints=[SQL("DEFAULT CURRENT_TIMESTAMP")])
    pl_name = CharField()
    pl_num_albums = IntegerField(constraints=[SQL("DEFAULT 0")])
    pl_num_artists = IntegerField(constraints=[SQL("DEFAULT 0")])
    pl_num_tracks = IntegerField(constraints=[SQL("DEFAULT 0")])
    pl_owner = CharField(null=True)
    pl_owner_url = CharField(null=True)

    class Meta:
        table_name = 'playlists'

class Tracks(BaseModel):
    album_name = CharField()
    album_uri = CharField()
    artist_name = CharField()
    artist_uri = CharField()
    duration_ms = IntegerField()
    track_name = CharField()
    track_uri = CharField(primary_key=True)

    class Meta:
        table_name = 'tracks'

