# Code generated by:
# python -m pwiz -e mysql -u root -H db -i -o -P db1
# Date: November 25, 2021 09:27PM
# Database: db1
# Peewee version: 3.14.8

from peewee import *
from connectDB import initPooledDB

database = initPooledDB()

class UnknownField(object):
    def __init__(self, *_, **__): pass

class BaseModel(Model):
    class Meta:
        database = database

class PlaylistContents(BaseModel):
    playlist_id = IntegerField()
    track_uri = CharField()

    class Meta:
        table_name = 'playlist_Contents'
        indexes = (
            (('playlist_id', 'track_uri'), True),
        )
        primary_key = CompositeKey('playlist_id', 'track_uri')

class Playlists(BaseModel):
    _name = CharField()
    duration_ms = IntegerField(constraints=[SQL("DEFAULT 0")])
    modified_at = DateTimeField(constraints=[SQL("DEFAULT CURRENT_TIMESTAMP")])
    num_albums = IntegerField(constraints=[SQL("DEFAULT 0")])
    num_artists = IntegerField(constraints=[SQL("DEFAULT 0")])
    num_edits = IntegerField(constraints=[SQL("DEFAULT 0")])
    num_followers = IntegerField(constraints=[SQL("DEFAULT 0")])
    num_tracks = IntegerField(constraints=[SQL("DEFAULT 0")])
    pid = AutoField()
    pl_description = CharField(null=True)
    pl_owner = CharField(null=True)
    pl_owner_url = CharField(null=True)

    class Meta:
        table_name = 'playlists'

class Tracks(BaseModel):
    album_name = CharField()
    album_uri = CharField()
    artist_name = CharField()
    artist_uri = CharField()
    duration_ms = IntegerField()
    track_name = CharField()
    track_uri = CharField(primary_key=True)

    class Meta:
        table_name = 'tracks'

